services:
  - type: web
    name: big-plan-tracker
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT -t public
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: MONGODB_URI
        sync: false  # Set this in Render dashboard
      - key: MONGODB_DATABASE
        value: bigplantracker
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health
    domains:
      - big-plan-tracker.onrender.com